//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Core/_Systems/Input System/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Prototype"",
            ""id"": ""4eaac555-a6bc-4f84-a2be-6b80a9609a7f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4a7e7e1c-3177-429c-863b-16fb3b2f4a45"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ac6fb8bd-2239-44c9-b56e-b792dd875e57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""e56c52bc-ea86-48c1-bd5c-80844ea3eadd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""6b6ad8c9-1324-466e-bca0-894abe3e2e9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""936a1664-2fd1-49cd-8319-801cbd2cde8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""d6ac92a3-664b-4749-a029-9567fca84d27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ledge"",
                    ""type"": ""Button"",
                    ""id"": ""6513baf3-0972-43c9-8d8d-9907f16b5e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a6275aee-430f-4ed1-8934-6d17acf16bdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""c3dce5cb-be12-48f7-b1b0-91c11cb27a59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d1019de7-3d19-4a58-89f3-98dd60122025"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""50d26625-26b5-4eeb-96a3-cb9108fb3d58"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9e1c2913-237c-4974-a125-965198808008"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bc4e7322-bc78-4df1-8827-ab75449d6d30"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""30dc34ad-3c63-4c7d-9f04-71d01c4b418c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""0d0a2078-f0de-48c9-a964-fb4030773b51"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5f6fe11a-f5c6-4944-bd4b-7033291434c6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a57ec60d-0194-41de-b4a7-740f1a95cadd"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0bfaabfc-44a6-4b21-b4d2-8e2f287c3c5c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df964267-e9ad-41a5-b1c5-6cadad0f30da"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3a133d4e-eac5-440a-8345-19b01a620660"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f82df64-cc9e-4028-bc50-ee7b9842839d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb8a1da7-35fd-4d32-92af-fca3a348e26f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c139614-aeb1-4f17-933d-22fbff500ce1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00220778-b8b4-41c1-87b3-3e02e87756f6"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea4b438a-5fff-45ae-88e7-42adfc4e7ebb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dedd85b8-a0d5-4e43-bd77-5ea95b9f08a8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ledge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8acb2c69-1b08-4249-abfe-3a2e9273ca11"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0da47e4-aea5-46f1-a164-4fa1b18464c2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Astrid"",
            ""id"": ""f13bf96c-2ee8-4a0b-ac47-159e8b038f82"",
            ""actions"": [
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""505cdbf9-6a58-4625-a609-7396e0bea11a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""70038058-2fb8-4e76-805d-0e83ce91c416"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""55562b89-cf5d-4507-956f-26793ac51976"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""084b83c8-e9a5-4920-b2c9-99a9329515a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""1197c24a-1753-426f-9f92-182cdbe7a0cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""98521835-55ec-4690-8f46-4e6d6e572b2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Button"",
                    ""id"": ""52ee462d-c426-4422-aea1-3403be3a2cbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""a9a32fb3-1f84-426d-a57a-bffa3dbf25df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d919602b-c84c-41b1-a919-d58661d3a3d2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80f849ed-f16a-4b2d-8858-c5c61eaafb22"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""d89f8f54-a191-4539-bbde-40619e61daef"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b68937de-9408-4cdd-871d-8b505b502306"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7dc987f3-d9df-4015-8532-0ec982c8bd4e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d63aebfb-c716-48c4-932e-338c63c57b6a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9b62fe54-9eb8-4ec9-a02c-4c9b30d48f33"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""605b55bd-2783-4ed6-b401-6ab211de4407"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0059093b-374f-4e97-9f3f-51c950b885cd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27c2611d-d8cc-4540-89d2-0c17b0187d55"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""54183238-ed54-4476-8589-1bc99676553c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""23e98ad9-4dd6-4037-8163-b81ded0dd39c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left Stick"",
                    ""id"": ""73daa389-8c76-4710-9f51-14731f4a24a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ac1016ac-fdfa-445e-a87b-21c852ebbd4c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3badb7f5-8597-40f6-ba99-099285e693e4"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""61a4eaa2-f137-4338-9615-cc51122dba9c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""78817598-0326-4688-bf73-40875730c297"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D-Pad"",
                    ""id"": ""8697bb45-93fb-460b-8e5a-8be854f0b60a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""838d6d8e-7cb9-4bc4-82a8-06b36899d2b1"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""81dbaa6b-5bee-40bd-b68b-6bd73a8ca3d9"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ca68505c-6f94-4558-b917-8ff05b5d8e1a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b933214b-a1e9-4809-bd3d-e08d1da42678"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fba78b37-029e-4e8b-bff3-d1c99f603fde"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46207908-56d4-4731-837b-24e00121f8cb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48ddc145-8fa5-4282-b934-e5ce5b322fd7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0689755d-114f-410b-ba47-b8d3739a68ce"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""857ddd22-1f00-42c2-9535-71d137fe9d3c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e897b55b-78cd-44cc-9a1f-f22272d8586e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1b09453-d001-4b66-8e7e-2c334aee4ad6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48268f40-5eb2-4ccf-bf68-d1400bf4c463"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee442cf6-a8bf-4405-a1a6-236eba5318ce"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3adc2277-53cf-41d4-a10d-1085b8ba7814"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""790f41d5-6576-4bd1-bc5f-17da00c7c028"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Prototype
        m_Prototype = asset.FindActionMap("Prototype", throwIfNotFound: true);
        m_Prototype_Movement = m_Prototype.FindAction("Movement", throwIfNotFound: true);
        m_Prototype_Jump = m_Prototype.FindAction("Jump", throwIfNotFound: true);
        m_Prototype_Crouch = m_Prototype.FindAction("Crouch", throwIfNotFound: true);
        m_Prototype_Aim = m_Prototype.FindAction("Aim", throwIfNotFound: true);
        m_Prototype_Shoot = m_Prototype.FindAction("Shoot", throwIfNotFound: true);
        m_Prototype_Melee = m_Prototype.FindAction("Melee", throwIfNotFound: true);
        m_Prototype_Ledge = m_Prototype.FindAction("Ledge", throwIfNotFound: true);
        m_Prototype_Interact = m_Prototype.FindAction("Interact", throwIfNotFound: true);
        m_Prototype_ChangeWeapon = m_Prototype.FindAction("ChangeWeapon", throwIfNotFound: true);
        // Astrid
        m_Astrid = asset.FindActionMap("Astrid", throwIfNotFound: true);
        m_Astrid_Interaction = m_Astrid.FindAction("Interaction", throwIfNotFound: true);
        m_Astrid_Movement = m_Astrid.FindAction("Movement", throwIfNotFound: true);
        m_Astrid_Crouch = m_Astrid.FindAction("Crouch", throwIfNotFound: true);
        m_Astrid_Aim = m_Astrid.FindAction("Aim", throwIfNotFound: true);
        m_Astrid_Shoot = m_Astrid.FindAction("Shoot", throwIfNotFound: true);
        m_Astrid_ChangeWeapon = m_Astrid.FindAction("ChangeWeapon", throwIfNotFound: true);
        m_Astrid_Turn = m_Astrid.FindAction("Turn", throwIfNotFound: true);
        m_Astrid_Escape = m_Astrid.FindAction("Escape", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Prototype
    private readonly InputActionMap m_Prototype;
    private IPrototypeActions m_PrototypeActionsCallbackInterface;
    private readonly InputAction m_Prototype_Movement;
    private readonly InputAction m_Prototype_Jump;
    private readonly InputAction m_Prototype_Crouch;
    private readonly InputAction m_Prototype_Aim;
    private readonly InputAction m_Prototype_Shoot;
    private readonly InputAction m_Prototype_Melee;
    private readonly InputAction m_Prototype_Ledge;
    private readonly InputAction m_Prototype_Interact;
    private readonly InputAction m_Prototype_ChangeWeapon;
    public struct PrototypeActions
    {
        private @InputActions m_Wrapper;
        public PrototypeActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Prototype_Movement;
        public InputAction @Jump => m_Wrapper.m_Prototype_Jump;
        public InputAction @Crouch => m_Wrapper.m_Prototype_Crouch;
        public InputAction @Aim => m_Wrapper.m_Prototype_Aim;
        public InputAction @Shoot => m_Wrapper.m_Prototype_Shoot;
        public InputAction @Melee => m_Wrapper.m_Prototype_Melee;
        public InputAction @Ledge => m_Wrapper.m_Prototype_Ledge;
        public InputAction @Interact => m_Wrapper.m_Prototype_Interact;
        public InputAction @ChangeWeapon => m_Wrapper.m_Prototype_ChangeWeapon;
        public InputActionMap Get() { return m_Wrapper.m_Prototype; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrototypeActions set) { return set.Get(); }
        public void SetCallbacks(IPrototypeActions instance)
        {
            if (m_Wrapper.m_PrototypeActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnCrouch;
                @Aim.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnAim;
                @Shoot.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnShoot;
                @Melee.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMelee;
                @Melee.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMelee;
                @Melee.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnMelee;
                @Ledge.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnLedge;
                @Ledge.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnLedge;
                @Ledge.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnLedge;
                @Interact.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnInteract;
                @ChangeWeapon.started -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_PrototypeActionsCallbackInterface.OnChangeWeapon;
            }
            m_Wrapper.m_PrototypeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Melee.started += instance.OnMelee;
                @Melee.performed += instance.OnMelee;
                @Melee.canceled += instance.OnMelee;
                @Ledge.started += instance.OnLedge;
                @Ledge.performed += instance.OnLedge;
                @Ledge.canceled += instance.OnLedge;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
            }
        }
    }
    public PrototypeActions @Prototype => new PrototypeActions(this);

    // Astrid
    private readonly InputActionMap m_Astrid;
    private IAstridActions m_AstridActionsCallbackInterface;
    private readonly InputAction m_Astrid_Interaction;
    private readonly InputAction m_Astrid_Movement;
    private readonly InputAction m_Astrid_Crouch;
    private readonly InputAction m_Astrid_Aim;
    private readonly InputAction m_Astrid_Shoot;
    private readonly InputAction m_Astrid_ChangeWeapon;
    private readonly InputAction m_Astrid_Turn;
    private readonly InputAction m_Astrid_Escape;
    public struct AstridActions
    {
        private @InputActions m_Wrapper;
        public AstridActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interaction => m_Wrapper.m_Astrid_Interaction;
        public InputAction @Movement => m_Wrapper.m_Astrid_Movement;
        public InputAction @Crouch => m_Wrapper.m_Astrid_Crouch;
        public InputAction @Aim => m_Wrapper.m_Astrid_Aim;
        public InputAction @Shoot => m_Wrapper.m_Astrid_Shoot;
        public InputAction @ChangeWeapon => m_Wrapper.m_Astrid_ChangeWeapon;
        public InputAction @Turn => m_Wrapper.m_Astrid_Turn;
        public InputAction @Escape => m_Wrapper.m_Astrid_Escape;
        public InputActionMap Get() { return m_Wrapper.m_Astrid; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AstridActions set) { return set.Get(); }
        public void SetCallbacks(IAstridActions instance)
        {
            if (m_Wrapper.m_AstridActionsCallbackInterface != null)
            {
                @Interaction.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnInteraction;
                @Movement.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnMovement;
                @Crouch.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnCrouch;
                @Aim.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnAim;
                @Shoot.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnShoot;
                @ChangeWeapon.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnChangeWeapon;
                @Turn.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnTurn;
                @Turn.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnTurn;
                @Turn.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnTurn;
                @Escape.started -= m_Wrapper.m_AstridActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_AstridActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_AstridActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_AstridActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
                @Turn.started += instance.OnTurn;
                @Turn.performed += instance.OnTurn;
                @Turn.canceled += instance.OnTurn;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public AstridActions @Astrid => new AstridActions(this);
    public interface IPrototypeActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnLedge(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
    }
    public interface IAstridActions
    {
        void OnInteraction(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
        void OnTurn(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
}
